function [TP,Lp_star,w_star_v,EU_vect,...
        E,V,EnteringF0,EnteringW0,EnteringLam_Idx,theta_star] = solveGivenU(...
        CV_tol,Niter,nPhi,nL,sep_pol,delta,pi_Phi,...
        Phi_grid,BETA,Lambda_vect,w_star_pre,U,pi_z,r,K,D,tau,w_star_pre_cons,Ppsi,nZ,init_Prod,b,rra)
  
  %Solve the SPP
  [TP,Lp_star,w_star_v,EU_vect] = solvePareto(CV_tol,Niter,nPhi,nL,sep_pol,delta,pi_Phi,...
    Phi_grid,BETA,Lambda_vect,w_star_pre,U,pi_z,r,K,D,tau,w_star_pre_cons);
  
  %Converting the solution from Lagrange multiplier space to promised value space
  [E,V] = calcEV(TP,nPhi,nL,Lambda_vect,U,sep_pol,Ppsi,K,D);
  
  %Solve the search problem
  [EnteringF0,EnteringW0,EnteringLam_Idx,theta_star] = ...
    solveSearch(nZ,init_Prod,delta,E,V,U,BETA,EU_vect,b,rra,Lambda_vect,sep_pol);
end