function [TP,iLp_star,w_star_v,...
        E,V,EnteringF0,EnteringW0,EnteringLam_Idx,theta_star] = solveGivenU(...
        CV_tol,Niter,nPhi,nL,sep_pol,delta,pi_Phi,...
        Phi_grid,BETA,Lambda_vect,w_star_pre,U,pi_z,r,K,D,tau,w_star_pre_cons,...
        Ppsi,nZ,init_Prod,b,rra,commitType,typeu)
  
  %Solve the SPP
  [TP,iLp_star,w_star_v] = solvePareto(CV_tol,Niter,nPhi,nL,sep_pol,delta,pi_Phi,...
    Phi_grid,BETA,Lambda_vect,w_star_pre,U,pi_z,r,K,D,tau,w_star_pre_cons,commitType);
  
  %Converting the solution from Lagrange multiplier space to promised value space
  [E,V] = calcEV(TP,nPhi,nL,Lambda_vect,U,sep_pol,Ppsi,K,D);
  
  %Solve the search problem
  [EnteringF0,EnteringW0,EnteringLam_Idx,theta_star] = ...
    solveSearch(nZ,init_Prod,delta,E,V,U,BETA,b,rra,Lambda_vect,sep_pol,typeu,pi_z);

end